version: "3.0"

services:
  # NGINX Service
  web-nginx:
    image: nginx:stable-alpine
    # container_name: web-nginx-forum
    working_dir: /usr/share/nginx/html
    volumes:
    #volume stockant les fichiers web du projet
      - "./apiFolder:/usr/share/nginx/html:ro"
      - "./.docker/nginx/log:/var/log/nginx"
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      #local: container
      - "8081:80"
    # depends_on:
    #   - db
    # links:
    # #lien vers le conteneur db
    #   - db:db
  # PHP Service
  web-forum-php-bloc:
#    build: .docker/php
    #container_name: web-forum-php
    build: 
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: web-forum-php-bloc
    working_dir: /usr/share/nginx/html
    # dns :
    #   - 127.0.0.1 
    volumes:
      - "./apiFolder:/usr/share/nginx/html"
    command:
      - /bin/sh
      - -c
      - |
        composer update --prefer-dist --no-progress & php-fpm
  #        pwd
  #        make -C /usr/share/nginx/html/ start-local
  #        cd /usr/share/nginx/html -- composer update --prefer-dist --no-progress  

  # MariaDB Service
  db:
    image: mariadb:10.5.12
    # container_name: web-db
    env_file:
      - ./.docker/mariadb/.env.dev
    ports:
      - "3306:3306"
    volumes:
    # volume de la base de données
      - ./db_data:/var/lib/mysql
    # environment:
    #   - MYSQL_ROOT_PASSWORD:root
    #   - MYSQL_DATABASE:api_forum
    #   - MYSQL_USER:forum
    #   - MYSQL_PASSWORD:root

      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - .docker/mariadb/data:/var/lib/mysql:rw

  adminer:
    image: adminer
    #    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: {}
#docker exec -it backend-web-forum-php-1 sh

#docker exec -it web-forum-php sh
#docker-compose exec php bin/console doctrine:migrations:migrate

# resultat

# marina_perez@LAPTOP-O1DI5RE4:~/dev/Forum-project-staging/back_end$ docker exec -it api_forum_adminer_1 sh
# /var/www/html $ php bin/console make:migration
# Could not open input file: bin/console
# /var/www/html $ 

# Start containers with docker-compose up -d
# Go into the php container with docker-compose exec php bash